services:
  auth:
    build: ./services/auth
    ports:
      - "8001:80"
    volumes:
      - ./services/auth:/app/
    depends_on:
      - localstack
    env_file:
      - ./services/auth/.env
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  command:
    build: ./services/command
    ports:
      - "8002:80"
    volumes:
      - ./services/command:/app/
    depends_on:
      - postgres
      - localstack
    env_file:
      - ./services/command/.env
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  query:
    build: ./services/query
    ports:
      - "8003:80"
    volumes:
      - ./services/query:/app/
    depends_on:
      - mongo
      - localstack
    env_file:
      - ./services/query/.env
    networks:
      - app-network
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  command-migrations:
    build: ./services/command
    volumes:
      - ./services/command:/app/
    depends_on:
      - postgres
    env_file:
      - ./services/command/.env
    networks:
      - app-network
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
    image: postgres:16.0-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    container_name: ${MONGO_CONTAINER_NAME:-postgres}
    image: mongo:8.0.0-rc11-jammy
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    networks:
      - app-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=${SERVICES-lambda,s3,apigateway,cloudwatch,dynamodb,sqs,kinesis,serverless,secretsmanager,ssm}
      - DEBUG=${DEBUG-}
      - LOCALSTACK_PERSISTENCE=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack_volume}:/var/lib/localstack"
      - "./mock/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh" # ready hook
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app-network

  motoserver:
    image: motoserver/moto:latest
    ports:
      - "5000:3000"
    environment:
      - MOTO_PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
