# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: run-postgres-init-scripts
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:16.0-alpine
        imagePullPolicy: "IfNotPresent" # "Always", "Never", "IfNotPresent"
        envFrom:
          - secretRef:
              name: postgres
        # kubectl exec it <pod_name> -- /bin/sh -n todo-app
        # command: ["/bin/sh"]
        # args: ["-c", "sleep 3600"]
        command: ["sh", "-c"]
        args:
          - |
            export PGPASSWORD=$POSTGRES_PASSWORD && \
            psql --host=postgres --username=$POSTGRES_USER \
                 --dbname=$POSTGRES_DB \
                 -f /scripts/databases.sql
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts/databases.sql
          subPath: databases.sql
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
  backoffLimit: 4
