apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - job.yaml

configMapGenerator:
  - name: postgres-init-scripts
    files:
      - migrations/databases.sql
