# job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: run-postgres-init-scripts
  namespace: todo-app
spec:
  template:
    spec:
      containers:
      - name: psql
        image: postgres:16.0-alpine
        envFrom:
          - secretRef:
              name: postgres
        command: ["sh", "-c"]
        args:
          - |
            export PGPASSWORD=$POSTGRES_PASSWORD && \
            psql --host=postgres --username=$POSTGRES_USER \
                 --dbname=$POSTGRES_DB \
                 -f /scripts/databases.sql
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts/databases.sql
          subPath: databases.sql
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-init-scripts
  backoffLimit: 4
