apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_DB: "cG9zdGdyZXM=" # echo -n 'postgres' | base64
  POSTGRES_USER: "cG9zdGdyZXM=" # echo -n 'postgres' | base64
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # echo -n 'postgres' | base64
