apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-command
spec:
  hosts:
    - todo-command
  http:
    - route:
        - destination:
            host: todo-command
            port:
              number: 8000
