apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-app
spec:
  hosts:
  - "*"
  gateways:
  - todo-app-gateway
  http:
  - match:
    - uri:
        prefix: /command
    route:
    - destination:
        host: todo-command
        port:
          number: 8000
