apiVersion: v1
kind: Service
metadata:
  name: todo-command
spec:
  selector:
    app: todo-command
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31553
  type: NodePort
