apiVersion: v1
kind: Service
metadata:
  name: todo-command
  labels:
    app: todo-command
    role: service
spec:
  selector:
    app: todo-command
    role: service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
